<?php
/**
 * Overhoren Installation Script
 * This script guides users through the installation process
 */

// Check if already installed
if (file_exists('config/database.php') && file_exists('config/auth.php')) {
    // Check if database is properly configured
    try {
        require_once 'config/database.php';
        $stmt = $GLOBALS['pdo']->query("SELECT COUNT(*) FROM tests");
        $isInstalled = true;
    } catch (Exception $e) {
        $isInstalled = false;
    }
    
    if ($isInstalled) {
        header('Location: /');
        exit;
    }
}

$step = $_GET['step'] ?? 1;
$error = '';
$success = '';

// Handle form submissions
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step == 1) {
        // Database configuration
        $host = $_POST['db_host'] ?? 'localhost';
        $username = $_POST['db_username'] ?? 'root';
        $password = $_POST['db_password'] ?? '';
        $database = $_POST['db_name'] ?? 'overhoren';
        
        // Test database connection
        try {
            $pdo = new PDO("mysql:host=$host;charset=utf8mb4", $username, $password);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create database if it doesn't exist
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$database`");
            $pdo->exec("USE `$database`");
            
            // Test if we can create tables
            $pdo->exec("CREATE TABLE IF NOT EXISTS test_connection (id INT)");
            $pdo->exec("DROP TABLE test_connection");
            
            // Save database configuration
            $config = "<?php
/**
 * Database Configuration
 * Generated by install.php
 */

\$host = " . var_export($host, true) . ";
\$username = " . var_export($username, true) . ";
\$password = " . var_export($password, true) . ";
\$database = " . var_export($database, true) . ";

try {
    \$pdo = new PDO(\"mysql:host=\$host;dbname=\$database;charset=utf8mb4\", \$username, \$password);
    \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    \$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
} catch (PDOException \$e) {
    die('Database connection failed: ' . \$e->getMessage());
}

/**
 * Execute a query with parameters
 */
function executeQuery(\$pdo, \$sql, \$params = []) {
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt;
}
?>";
            
            file_put_contents('config/database.php', $config);
            $success = 'Database configuration saved successfully!';
            $step = 2;
            
        } catch (Exception $e) {
            $error = 'Database connection failed: ' . $e->getMessage();
        }
    } elseif ($step == 2) {
        // Install database schema and data
        try {
            require_once 'config/database.php';
            
            // Install schema - read and clean the schema file
            $schema = file_get_contents('database/schema.sql');
            
            // Remove CREATE DATABASE and USE statements since we're already connected to the database
            $schema = preg_replace('/CREATE DATABASE IF NOT EXISTS [^;]+;/i', '', $schema);
            $schema = preg_replace('/USE [^;]+;/i', '', $schema);
            
            // Split into individual statements and execute them
            $statements = array_filter(array_map('trim', explode(';', $schema)));
            foreach ($statements as $statement) {
                if (!empty($statement)) {
                    $GLOBALS['pdo']->exec($statement);
                }
            }
            
            // Install sample data if requested
            if (isset($_POST['install_sample_data'])) {
                $data = file_get_contents('database/data.sql');
                // Clean the data file as well
                $data = preg_replace('/CREATE DATABASE IF NOT EXISTS [^;]+;/i', '', $data);
                $data = preg_replace('/USE [^;]+;/i', '', $data);
                
                $dataStatements = array_filter(array_map('trim', explode(';', $data)));
                foreach ($dataStatements as $statement) {
                    if (!empty($statement)) {
                        $GLOBALS['pdo']->exec($statement);
                    }
                }
            }
            
            $success = 'Database installed successfully!';
            $step = 3;
            
        } catch (Exception $e) {
            $error = 'Database installation failed: ' . $e->getMessage();
        }
    } elseif ($step == 3) {
        // Create admin user
        try {
            require_once 'config/database.php';
            require_once 'config/auth.php';
            
            $username = $_POST['admin_username'] ?? '';
            $password = $_POST['admin_password'] ?? '';
            $email = $_POST['admin_email'] ?? '';
            $fullName = $_POST['admin_full_name'] ?? '';
            
            if (empty($username) || empty($password)) {
                throw new Exception('Username and password are required');
            }
            
            if (strlen($password) < 6) {
                throw new Exception('Password must be at least 6 characters long');
            }
            
            // Create admin user
            $userId = createAdminUser($username, $password, $email, $fullName);
            
            if ($userId) {
                $success = 'Admin user created successfully! Installation complete.';
                $step = 4;
            } else {
                throw new Exception('Failed to create admin user');
            }
            
        } catch (Exception $e) {
            $error = 'Admin user creation failed: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Overhoren Installatie</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        
        .install-container {
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            max-width: 500px;
            width: 100%;
            overflow: hidden;
        }
        
        .header {
            background: #2c3e50;
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        .header h1 {
            font-size: 28px;
            margin-bottom: 10px;
        }
        
        .header p {
            opacity: 0.9;
            font-size: 16px;
        }
        
        .content {
            padding: 40px;
        }
        
        .step-indicator {
            display: flex;
            justify-content: center;
            margin-bottom: 30px;
        }
        
        .step {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 10px;
            font-weight: bold;
            position: relative;
        }
        
        .step.active {
            background: #3498db;
            color: white;
        }
        
        .step.completed {
            background: #27ae60;
            color: white;
        }
        
        .step.pending {
            background: #ecf0f1;
            color: #7f8c8d;
        }
        
        .step:not(:last-child)::after {
            content: '';
            position: absolute;
            top: 50%;
            left: 100%;
            width: 20px;
            height: 2px;
            background: #ecf0f1;
            transform: translateY(-50%);
        }
        
        .step.completed:not(:last-child)::after {
            background: #27ae60;
        }
        
        .form-group {
            margin-bottom: 20px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 600;
            color: #2c3e50;
        }
        
        .form-group input,
        .form-group select {
            width: 100%;
            padding: 12px 15px;
            border: 2px solid #ecf0f1;
            border-radius: 8px;
            font-size: 16px;
            transition: border-color 0.3s ease;
        }
        
        .form-group input:focus,
        .form-group select:focus {
            outline: none;
            border-color: #3498db;
        }
        
        .checkbox-group {
            display: flex;
            align-items: center;
            margin: 20px 0;
        }
        
        .checkbox-group input[type="checkbox"] {
            width: auto;
            margin-right: 10px;
        }
        
        .btn {
            background: #3498db;
            color: white;
            border: none;
            padding: 15px 30px;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: background-color 0.3s ease;
            width: 100%;
        }
        
        .btn:hover {
            background: #2980b9;
        }
        
        .btn:disabled {
            background: #bdc3c7;
            cursor: not-allowed;
        }
        
        .alert {
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        
        .alert.error {
            background: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
        }
        
        .alert.success {
            background: #d4edda;
            color: #155724;
            border: 1px solid #c3e6cb;
        }
        
        .info-box {
            background: #e3f2fd;
            border: 1px solid #bbdefb;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
        }
        
        .info-box h3 {
            color: #1976d2;
            margin-bottom: 10px;
        }
        
        .info-box p {
            color: #1565c0;
            line-height: 1.6;
        }
        
        .success-page {
            text-align: center;
        }
        
        .success-page .icon {
            font-size: 64px;
            color: #27ae60;
            margin-bottom: 20px;
        }
        
        .success-page h2 {
            color: #2c3e50;
            margin-bottom: 20px;
        }
        
        .success-page .btn {
            display: inline-block;
            width: auto;
            padding: 12px 24px;
            text-decoration: none;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="install-container">
        <div class="header">
            <h1>🚀 Overhoren Installatie</h1>
            <p>Welkom bij de installatie van je Nederlandse oefenwebsite</p>
        </div>
        
        <div class="content">
            <!-- Step Indicator -->
            <div class="step-indicator">
                <div class="step <?= $step >= 1 ? ($step > 1 ? 'completed' : 'active') : 'pending' ?>">1</div>
                <div class="step <?= $step >= 2 ? ($step > 2 ? 'completed' : 'active') : 'pending' ?>">2</div>
                <div class="step <?= $step >= 3 ? ($step > 3 ? 'completed' : 'active') : 'pending' ?>">3</div>
                <div class="step <?= $step >= 4 ? 'active' : 'pending' ?>">4</div>
            </div>
            
            <?php if ($error): ?>
                <div class="alert error"><?= htmlspecialchars($error) ?></div>
            <?php endif; ?>
            
            <?php if ($success): ?>
                <div class="alert success"><?= htmlspecialchars($success) ?></div>
            <?php endif; ?>
            
            <?php if ($step == 1): ?>
                <!-- Step 1: Database Configuration -->
                <h2>Database Configuratie</h2>
                <p>Voer je database gegevens in. Voor XAMPP zijn de standaard instellingen meestal correct.</p>
                
                <form method="POST">
                    <div class="form-group">
                        <label for="db_host">Database Host:</label>
                        <input type="text" id="db_host" name="db_host" value="localhost" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_username">Gebruikersnaam:</label>
                        <input type="text" id="db_username" name="db_username" value="root" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="db_password">Wachtwoord:</label>
                        <input type="password" id="db_password" name="db_password">
                    </div>
                    
                    <div class="form-group">
                        <label for="db_name">Database Naam:</label>
                        <input type="text" id="db_name" name="db_name" value="overhoren" required>
                    </div>
                    
                    <button type="submit" class="btn">Database Testen & Doorgaan</button>
                </form>
                
            <?php elseif ($step == 2): ?>
                <!-- Step 2: Database Installation -->
                <h2>Database Installatie</h2>
                <p>De database verbinding is succesvol! Nu gaan we de tabellen en data installeren.</p>
                
                <div class="info-box">
                    <h3>📊 Wat wordt geïnstalleerd?</h3>
                    <p>• Database tabellen (tests, questions, admin_users)<br>
                    • Optioneel: Nederlandse voorbeelddata (5 toetsen met 25 vragen)</p>
                </div>
                
                <form method="POST">
                    <div class="checkbox-group">
                        <input type="checkbox" id="install_sample_data" name="install_sample_data" checked>
                        <label for="install_sample_data">Nederlandse voorbeelddata installeren</label>
                    </div>
                    
                    <button type="submit" class="btn">Database Installeren</button>
                </form>
                
            <?php elseif ($step == 3): ?>
                <!-- Step 3: Admin User Creation -->
                <h2>Admin Gebruiker Aanmaken</h2>
                <p>Maak je eerste admin gebruiker aan om toegang te krijgen tot het beheerpaneel.</p>
                
                <form method="POST">
                    <div class="form-group">
                        <label for="admin_username">Gebruikersnaam:</label>
                        <input type="text" id="admin_username" name="admin_username" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="admin_password">Wachtwoord:</label>
                        <input type="password" id="admin_password" name="admin_password" minlength="6" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="admin_email">Email (optioneel):</label>
                        <input type="email" id="admin_email" name="admin_email">
                    </div>
                    
                    <div class="form-group">
                        <label for="admin_full_name">Volledige Naam (optioneel):</label>
                        <input type="text" id="admin_full_name" name="admin_full_name">
                    </div>
                    
                    <button type="submit" class="btn">Admin Gebruiker Aanmaken</button>
                </form>
                
            <?php elseif ($step == 4): ?>
                <!-- Step 4: Installation Complete -->
                <div class="success-page">
                    <div class="icon">✅</div>
                    <h2>Installatie Voltooid!</h2>
                    <p>Overhoren is succesvol geïnstalleerd en klaar voor gebruik.</p>
                    
                    <div class="info-box">
                        <h3>🎉 Wat kun je nu doen?</h3>
                        <p>• <strong>Beheerpaneel:</strong> Beheer toetsen en vragen<br>
                        • <strong>Hoofdsite:</strong> Bekijk beschikbare toetsen<br>
                        • <strong>Inloggen:</strong> Gebruik je admin credentials</p>
                    </div>
                    
                    <a href="/" class="btn">Naar Hoofdsite</a>
                    <a href="/admin" class="btn" style="background: #27ae60; margin-left: 10px;">Naar Beheerpaneel</a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>
